#!/usr/bin/env python3
"""Generate minimal host bindings for canonical bootstrap-development skills."""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path


CATALOG_PATH = Path(
    "development/bootstrap-agent/skill-catalog/SKILL_REGISTRY.yaml"
)
BINDING_ROOTS = (Path(".agents/skills"), Path(".codex/skills"))
GENERATED_NOTICE = "<!-- Generated by development/tools/generate_host_bindings.py. -->"


@dataclass(frozen=True)
class CatalogSkill:
    skill_id: str
    canonical_path: Path


def parse_catalog(path: Path) -> list[CatalogSkill]:
    """Read the two catalog fields needed by the binding generator."""

    entries: list[CatalogSkill] = []
    current_id: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        id_match = re.match(r"^  - skill_id:\s*(\S+)\s*$", line)
        if id_match:
            current_id = id_match.group(1)
            continue
        path_match = re.match(r"^    canonical_path:\s*(\S+)\s*$", line)
        if path_match and current_id:
            entries.append(CatalogSkill(current_id, Path(path_match.group(1))))
            current_id = None
    if not entries:
        raise ValueError(f"{path}: no skills found")
    ids = [entry.skill_id for entry in entries]
    if len(ids) != len(set(ids)):
        raise ValueError(f"{path}: duplicate skill IDs")
    return entries


def front_matter(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    name_match = re.search(r"^name:\s*(.+?)\s*$", text, re.MULTILINE)
    description_match = re.search(
        r"^description:\s*(.+?)\s*$", text, re.MULTILINE
    )
    return (
        name_match.group(1).strip() if name_match else path.parent.name,
        description_match.group(1).strip()
        if description_match
        else f"Canonical bootstrap skill {path.parent.name}.",
    )


def binding_text(entry: CatalogSkill, root: Path) -> str:
    source = entry.canonical_path / "SKILL.md"
    name, description = front_matter(root / source)
    return "\n".join(
        [
            "---",
            f"name: {name}",
            f"description: {description}",
            "---",
            "",
            GENERATED_NOTICE,
            "",
            "# Host Binding",
            "",
            f"Canonical source: `{entry.canonical_path.as_posix()}/SKILL.md`",
            "",
            "Read and follow the complete canonical source above. This file is a",
            "host-discovery binding only and carries no independent behavior or authority.",
            "",
        ]
    )


def expected_bindings(root: Path) -> dict[Path, str]:
    catalog = parse_catalog(root / CATALOG_PATH)
    expected: dict[Path, str] = {}
    for entry in catalog:
        source = root / entry.canonical_path / "SKILL.md"
        if not source.is_file():
            raise FileNotFoundError(f"missing canonical skill source: {source}")
        for binding_root in BINDING_ROOTS:
            expected[binding_root / entry.skill_id / "SKILL.md"] = binding_text(
                entry, root
            )
    return expected


def check(root: Path) -> list[str]:
    expected = expected_bindings(root)
    messages: list[str] = []
    for path, content in expected.items():
        target = root / path
        if not target.is_file():
            messages.append(f"missing host binding: {path}")
        elif target.read_text(encoding="utf-8") != content:
            messages.append(f"stale host binding: {path}")
    expected_paths = set(expected)
    for binding_root in BINDING_ROOTS:
        root_path = root / binding_root
        if not root_path.exists():
            continue
        for target in root_path.glob("*/SKILL.md"):
            relative = target.relative_to(root)
            if relative not in expected_paths:
                messages.append(f"orphan host binding: {relative}")
    return messages


def generate(root: Path) -> None:
    expected = expected_bindings(root)
    for binding_root in BINDING_ROOTS:
        target = root / binding_root
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True)
    for path, content in expected.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--check", action="store_true", help="Check without writing")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = Path(args.root).resolve()
    if args.check:
        messages = check(root)
        if messages:
            for message in messages:
                print(f"FAIL {message}", file=sys.stderr)
            return 1
        print("host bindings are current")
        return 0
    generate(root)
    print(f"generated host bindings in {', '.join(map(str, BINDING_ROOTS))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
